// Generated by CoffeeScript 1.6.1
(function() {
  var PSD, clipping, exec, fs, layer, path, psd, psd_dirname, _i, _len, _ref;

  fs = require('fs');

  path = require('path');

  exec = require('child_process').exec;

  PSD = require(__dirname + '/../lib/psd.js').PSD;

  PSD.DEBUG = false;

  if (process.argv.length === 2) {
    console.log("Please specify an input file");
    process.exit();
  }

  psd = PSD.fromFile(process.argv[2]);

  psd.setOptions({
    layerImages: true,
    onlyVisibleLayers: true
  });

  psd.parse();

  psd_dirname = path.dirname(process.argv[2]);

  clipping = 0;

  _ref = psd['layers'];
  for (_i = 0, _len = _ref.length; _i < _len; _i++) {
    layer = _ref[_i];
    if (layer.blendMode.clipping === 1) {
      clipping++;
    }
  }

  console.log("" + clipping + " clipping items");

  fs.open('./clippingtext.txt', 'a', 777, function(e, id) {
    return fs.write(id, "" + process.argv[2] + " " + clipping + "\n", null, 'utf8', function() {
      return {};
    });
  });

}).call(this);
