// Generated by CoffeeScript 1.6.1
(function() {
  var PSD, fs, psd, start;

  fs = require('fs');

  PSD = require(__dirname + '/../src/psd.js');

  if (process.argv.length === 2) {
    console.log("Please specify an input file");
    process.exit();
  }

  psd = PSD.fromFile(process.argv[2]);

  start = (new Date()).getTime();

  psd.toFile(__dirname + '/output.png', function() {
    var end;
    end = (new Date()).getTime();
    return console.log("PSD flattened to output.png in " + (end - start) + "ms");
  });

}).call(this);
