// Generated by CoffeeScript 1.6.1
(function() {
  var PSD, exec, fs, psd;

  fs = require('fs');

  exec = require('child_process').exec;

  PSD = require(__dirname + '/../lib/psd.js').PSD;

  PSD.DEBUG = true;

  if (process.argv.length === 2) {
    console.log("Please specify an input file");
    process.exit();
  }

  psd = PSD.fromFile(process.argv[2]);

  psd.setOptions({
    layerImages: true,
    onlyVisibleLayers: true
  });

  psd.parse();

  exec("mkdir -p " + __dirname + "/output", function() {
    var layer, _i, _len, _ref, _results;
    _ref = psd.layers;
    _results = [];
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      layer = _ref[_i];
      if (!layer.image) {
        continue;
      }
      _results.push((function(layer) {
        return layer.image.toFile(__dirname + ("/output/" + layer.name + ".png"), function() {
          return console.log("Layer " + layer.name + " output to file.");
        });
      })(layer));
    }
    return _results;
  });

}).call(this);
