// Generated by CoffeeScript 1.6.1
(function() {
  var PSD, assets_directory, basename, design_file, fs, image_file_name, image_name, input_psd_file, layer, output_dir, path, png_file, psd, _i, _len, _ref;

  fs = require('fs');

  path = require('path');

  PSD = require('../src/psd');

  input_psd_file = process.argv[2];

  output_dir = "/tmp/psdjs";

  basename = "output";

  console.log("Input psd file is " + input_psd_file);

  console.log("Output directory is " + output_dir);

  if (!fs.existsSync('/tmp/psdjs')) {
    fs.mkdirSync('/tmp/psdjs');
  }

  if (!fs.existsSync('/tmp/psdjs/assets')) {
    fs.mkdirSync('/tmp/psdjs/assets');
  }

  psd = PSD.fromFile(input_psd_file);

  psd.setOptions({
    layerImages: true,
    onlyVisibleLayers: true
  });

  png_file = path.join(output_dir, "" + basename + ".png");

  design_file = path.join(output_dir, "" + basename + ".json");

  assets_directory = path.join(output_dir, "assets");

  psd.parse();

  fs.writeFileSync(design_file, JSON.stringify(psd));

  psd.toFileSync(png_file);

  _ref = psd.layers;
  for (_i = 0, _len = _ref.length; _i < _len; _i++) {
    layer = _ref[_i];
    if (!layer.image) {
      continue;
    }
    image_name = layer.name.replace(/[^0-9a-zA-Z]/g, '_');
    image_file_name = path.join(assets_directory, "" + image_name + "_" + layer.layerId + ".png");
    layer.image.toFileSync(image_file_name);
  }

}).call(this);
