// Generated by CoffeeScript 1.6.1
(function() {
  var PSD, data, fs, psd;

  fs = require('fs');

  PSD = require(__dirname + '/../src/psd.js').PSD;

  PSD.DEBUG = true;

  if (process.argv.length === 2) {
    console.log("Please specify an input file");
    process.exit();
  }

  psd = PSD.fromFile(process.argv[2]);

  psd.parse();

  data = psd.toJSON();

  fs.writeFile(__dirname + "/output.json", JSON.stringify(data, null, "\t"), function(err) {
    return console.log("JSON data saved to output.json");
  });

}).call(this);
