// Generated by CoffeeScript 1.6.1
(function() {
  var PSDBrightnessContrast;

  PSDBrightnessContrast = (function() {

    function PSDBrightnessContrast(layer, length) {
      this.layer = layer;
      this.length = length;
      this.file = this.layer.file;
      this.data = {};
    }

    PSDBrightnessContrast.prototype.parse = function() {
      this.data.brightness = this.file.readShortInt();
      this.data.contrast = this.file.readShortInt();
      this.data.meanValue = this.file.readShortInt();
      this.data.labColor = this.file.readShortInt();
      return this.data;
    };

    return PSDBrightnessContrast;

  })();

  module.exports = PSDBrightnessContrast;

}).call(this);
