// Generated by CoffeeScript 1.6.1
(function() {
  var EngineDataParser;

  EngineDataParser = (function() {

    function EngineDataParser() {}

    EngineDataParser.parseData = function(data) {
      var root, tokens;
      data = data.replace(/(\r\n|\n|\r)/gm, ' ');
      data = data.replace(/\s{2,}/g, ' ');
      tokens = data.split(' ');
      root = {};
      EngineDataParser.parseTokens(tokens, root);
      return root;
    };

    EngineDataParser.parseTokens = function(tokens, parent, parent_is_array) {
      var currentToken;
      if (parent_is_array == null) {
        parent_is_array = false;
      }
      while (tokens[0] === "") {
        tokens.splice(0, 1);
      }
      currentToken = tokens[0];
      if (currentToken === ">>" && !parent_is_array) {

      }
    };

    return EngineDataParser;

  })();

  module.exports = EngineDataParser;

}).call(this);
