// Generated by CoffeeScript 1.6.1
(function() {
  var PSDExposure, assert;

  assert = require('../psdassert');

  PSDExposure = (function() {

    function PSDExposure(layer, length) {
      this.layer = layer;
      this.length = length;
      this.file = this.layer.file;
    }

    PSDExposure.prototype.parse = function() {
      var version;
      version = this.file.parseInt();
      assert(version === 1);
      return {
        exposure: this.file.parseInt(),
        offset: this.file.parseInt(),
        gamma: this.file.parseInt()
      };
    };

    return PSDExposure;

  })();

  module.exports = PSDExposure;

}).call(this);
