// Generated by CoffeeScript 1.6.1
(function() {
  var PSDDescriptor, PSDFillColor, Parser, assert;

  PSDDescriptor = require('../psddescriptor');

  Parser = require('../parser');

  assert = require('../psdassert');

  PSDFillColor = (function() {

    function PSDFillColor(layer, length) {
      this.layer = layer;
      this.length = length;
      this.file = this.layer.file;
    }

    PSDFillColor.prototype.parse = function() {
      var fill_opacity, opacity_hex;
      opacity_hex = parseInt(this.file.read(1));
      fill_opacity = Math.round(opacity_hex * 100 / 255);
      return fill_opacity;
    };

    return PSDFillColor;

  })();

  module.exports = PSDFillColor;

}).call(this);
