// Generated by CoffeeScript 1.6.1
(function() {
  var PSDDescriptor, PSDGradient, Parser, assert;

  PSDDescriptor = require('../psddescriptor');

  Parser = require('../parser');

  assert = require('../psdassert');

  PSDGradient = (function() {

    function PSDGradient(layer, length) {
      this.layer = layer;
      this.length = length;
      this.file = this.layer.file;
    }

    PSDGradient.prototype.parse = function() {
      var descriptor, gradient, version;
      version = this.file.readInt();
      assert(version === 16);
      descriptor = (new PSDDescriptor(this.file)).parse();
      gradient = Parser.parseGradient(descriptor);
      return gradient;
    };

    return PSDGradient;

  })();

  module.exports = PSDGradient;

}).call(this);
