// Generated by CoffeeScript 1.6.1
(function() {
  var PSDHueSaturation, assert;

  assert = require('../psdassert');

  PSDHueSaturation = (function() {

    function PSDHueSaturation(layer, length) {
      this.layer = layer;
      this.length = length;
      this.file = this.layer.file;
    }

    PSDHueSaturation.prototype.parse = function() {
      var i, j, version, _i, _j, _k;
      version = this.file.readShortInt();
      assert(version === 2);
      this.data.colorization = this.file.readBoolean();
      this.file.seek(1);
      this.data.hue = this.file.readShortInt();
      this.data.saturation = this.file.readShortInt();
      this.data.lightness = this.file.readShortInt();
      this.data.masterHue = this.file.readShortInt();
      this.data.masterSaturation = this.file.readShortInt();
      this.data.masterLightness = this.file.readShortInt();
      this.data.rangeValues = [];
      this.data.settingValues = [];
      for (i = _i = 0; _i < 6; i = ++_i) {
        this.data.rangeValues[i] = [];
        this.data.settingValues[i] = [];
        for (j = _j = 0; _j < 4; j = ++_j) {
          this.data.rangeValues[i][j] = this.file.readShortInt();
        }
        for (j = _k = 0; _k < 3; j = ++_k) {
          this.data.settingValues[i][j] = this.file.readShortInt();
        }
      }
      return this.data;
    };

    return PSDHueSaturation;

  })();

  module.exports = PSDHueSaturation;

}).call(this);
