// Generated by CoffeeScript 1.6.1
(function() {
  var PSDInvert;

  PSDInvert = (function() {

    function PSDInvert(layer, length) {
      this.layer = layer;
      this.length = length;
      this.file = this.layer.file;
    }

    PSDInvert.prototype.parse = function() {
      return true;
    };

    return PSDInvert;

  })();

  module.exports = PSDInvert;

}).call(this);
