// Generated by CoffeeScript 1.6.1
(function() {
  var PSDDescriptor, PSDPattern, Parser, assert;

  PSDDescriptor = require('../psddescriptor');

  Parser = require('../parser');

  assert = require('../psdassert');

  PSDPattern = (function() {

    function PSDPattern(layer, length) {
      this.layer = layer;
      this.length = length;
      this.file = this.layer.file;
    }

    PSDPattern.prototype.parse = function() {
      var descriptor, version;
      version = this.file.readInt();
      assert(version === 16);
      descriptor = (new PSDDescriptor(this.file)).parse();
      return Parser.parsePattern(descriptor);
    };

    return PSDPattern;

  })();

  module.exports = PSDPattern;

}).call(this);
