// Generated by CoffeeScript 1.6.1
(function() {
  var PSDPhotoFilter, assert;

  assert = require('../psdassert');

  PSDPhotoFilter = (function() {

    function PSDPhotoFilter(layer, length) {
      this.layer = layer;
      this.length = length;
      this.file = this.layer.file;
    }

    PSDPhotoFilter.prototype.parse = function() {
      var data, version;
      version = this.file.parseInt();
      assert(version === 3);
      data = {};
      data.color = {
        x: this.file.readInt(),
        y: this.file.readInt(),
        z: this.file.readInt()
      };
      data.density = this.file.readInt();
      data.preserveLuminosity = this.file.readBoolean();
      return data;
    };

    return PSDPhotoFilter;

  })();

  module.exports = PSDPhotoFilter;

}).call(this);
