// Generated by CoffeeScript 1.6.1
(function() {
  var PSDPosterize, assert;

  assert = require('../psdassert');

  PSDPosterize = (function() {

    function PSDPosterize(layer, length) {
      this.layer = layer;
      this.length = length;
      this.file = this.layer.file;
      this.data = {};
    }

    PSDPosterize.prototype.parse = function() {
      this.data.levels = this.file.readShortInt();
      assert(this.data.levels >= 2 && this.data.levels <= 255);
      this.file.seek(2);
      return this.data;
    };

    return PSDPosterize;

  })();

  module.exports = PSDPosterize;

}).call(this);
