// Generated by CoffeeScript 1.6.1
(function() {
  var PSDSelectiveColor, assert;

  assert = require('../psdassert');

  PSDSelectiveColor = (function() {

    function PSDSelectiveColor(layer, length) {
      this.layer = layer;
      this.length = length;
      this.file = this.layer.file;
      this.data = {
        cyanCorrection: [],
        magentaCorrection: [],
        yellowCorrection: [],
        blackCorrection: []
      };
    }

    PSDSelectiveColor.prototype.parse = function() {
      var i, version, _i;
      version = this.file.readShortInt();
      assert(version === 1);
      this.data.correctionMethod = this.file.readShortInt();
      for (i = _i = 0; _i < 10; i = ++_i) {
        this.data.cyanCorrection.push(this.file.readShortInt());
        this.data.magentaCorrection.push(this.file.readShortInt());
        this.data.yellowCorrection.push(this.file.readShortInt());
        this.data.blackCorrection.push(this.file.readShortInt());
      }
      return this.data;
    };

    return PSDSelectiveColor;

  })();

  module.exports = PSDSelectiveColor;

}).call(this);
