// Generated by CoffeeScript 1.6.1
(function() {
  var PSDDescriptor, PSDSolidColor, assert;

  PSDDescriptor = require('../psddescriptor');

  assert = require('../psdassert');

  PSDSolidColor = (function() {

    function PSDSolidColor(layer, length) {
      this.layer = layer;
      this.length = length;
      this.file = this.layer.file;
    }

    PSDSolidColor.prototype.parse = function() {
      var descriptor, version;
      version = this.file.readInt();
      assert(version === 16);
      descriptor = (new PSDDescriptor(this.file)).parse();
      return descriptor.color;
    };

    return PSDSolidColor;

  })();

  module.exports = PSDSolidColor;

}).call(this);
