// Generated by CoffeeScript 1.6.1
(function() {
  var PSDThreshold, assert;

  assert = require('../psdassert');

  PSDThreshold = (function() {

    function PSDThreshold(layer, length) {
      this.layer = layer;
      this.length = length;
      this.file = this.layer.file;
      this.data = {};
    }

    PSDThreshold.prototype.parse = function() {
      this.data.level = this.file.readShortInt();
      assert(this.data.level >= 1 && this.data.level <= 255);
      this.file.seek(2);
      return this.data;
    };

    return PSDThreshold;

  })();

  module.exports = PSDThreshold;

}).call(this);
