// Generated by CoffeeScript 1.6.1
(function() {
  var PSDDescriptor, PSDVibrance, Parser, assert;

  PSDDescriptor = require('../psddescriptor');

  Parser = require('../parser');

  assert = require('../psdassert');

  PSDVibrance = (function() {

    function PSDVibrance(layer, length) {
      this.layer = layer;
      this.length = length;
      this.file = this.layer.file;
    }

    PSDVibrance.prototype.parse = function() {
      var version;
      version = this.file.readInt();
      assert(version === 16);
      return (new PSDDescriptor(this.file)).parse();
    };

    return PSDVibrance;

  })();

  module.exports = PSDVibrance;

}).call(this);
