// Generated by CoffeeScript 1.6.1
(function() {
  var Log;

  Log = (function() {

    function Log() {}

    Log.DEBUG = false;

    Log.debug = Log.log = function() {
      return this.output("log", arguments);
    };

    Log.output = function(method, data) {
      if (this.DEBUG) {
        return console[method].apply(null, data);
      }
    };

    return Log;

  })();

  module.exports = Log;

}).call(this);
