// Generated by CoffeeScript 1.6.1
(function() {
  var assert;

  assert = (function(assert) {
    if (typeof exports !== "undefined" && exports !== null) {
      return require('assert');
    }
    assert = function(test) {
      if (test !== true) {
        throw "Assertion error";
      }
    };
    assert.equal = function(actual, expected) {
      if (actual !== expected) {
        throw "Assertion error";
      }
    };
    return assert;
  })(assert);

  module.exports = assert;

}).call(this);
